### ISSUE TITLE
Web-version

### ISSUE THREAD

**Issue by knandersen** [olt/mgreel#1]
Hi Oliver,
Amazing work! I've been looking for a way to create an easy-to-use tool for Morphagene users to create reels. Until now I'd worked with python-scripts, but would prefer something that just runs in a browser. I couldn't figure out how to do the audio-part using web technologies, but then I came across your work, and saw that you were looking for someone to do the front end part.

I've started working on what could become a web-version over here: https://github.com/knandersen/mgreelweb

I'm curious what the best would be in terms of attributing your work? As far as I can see I can't use your code as a module, so I started writing it into my react website. Ultimately I'd prefer if everything runs in the users browser, so that there are no privacy concerns.

Let me know what you think! It's very much work in progress.

In advance, thanks,
Kevin

**Comment by knandersen** [comment]
I think I've got a first working prototype! Check it out here: https://knandersen.github.io/mgreelweb/

Just drag some wav-files in and hopefully you'll be asked to download a file!

**Comment by lorenzos** [comment]
[Ehm, I don't want to be that guy, but...](https://github.com/lorenzos/mgreel)

**Comment by knandersen** [comment]
aw man, wish I would've known before I started working on it...

is it deployed anywhere? I know some people in the Make Noise User Group on Facebook would really like a tool like this, but without having to download/install anything.

**Comment by lorenzos** [comment]
Sorry, I was in contact with the original author via email, so I didn't opened an issue here. I see we basically had the same approach :)

At the moment is not deployed anywhere, but the plan is to add it to my Morphagene options editor you see here: <https://www.lorenzostanco.com/lab/morphagene/>

In fact, I thought to do it this weekend. I'd be glad if you could tell people on Facebook once it's ready (I do not have an account), I'll let you know here.

**Comment by knandersen** [comment]
nice, cool website! I'd be happy to let folks know once you're ready 🙂

**Comment by lorenzos** [comment]
Done! <https://www.lorenzostanco.com/lab/morphagene/#mgreel>

The link above opens the reel assembler directly. The base link still points to the options editor. I borrowed your idea of natural-sorting input files :wink:

**Comment by knandersen** [comment]
Amazing, thanks for sharing! And at least I got to contribute a tiny bit 😄

**Comment by olt** [comment]
I'm sorry Kevin, we should have discussed this here. :-/
Thank you both for your work!
